### ISSUE TITLE
how do you use it

### ISSUE THREAD

**Issue by Pickymarker** [DP44/KabulClient#3]
how do you use it on the latest version of vrchat

**Comment by DP44** [comment]
It should just work how you would load any other mod using melonloader. If you're wondering how to open the menu the key is Insert.

**Comment by Pickymarker** [comment]
does the avatar clone work

**Comment by Pickymarker** [comment]
dp44 do you know any clients that are free and have avatar search

**Comment by DP44** [comment]
i know emm has avatar search and that client is free, but it's also a dogshit client so keep that in mind.

**Comment by Pickymarker** [comment]
i tried to get 
Nicky-s-Menu but i don't know how to get the dll for it on there github

**Comment by DP44** [comment]
closing since it's not really a problem with Kabul specifically.
